include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - unawaited_futures
    - public_member_api_docs
    - require_trailing_commas

analyzer:
  exclude: [example_flutter/**, '**/*.g.dart']