on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-dart
          ref: ${{ inputs.ref || github.ref }}

      - uses: dart-lang/setup-dart@v1.8.0

      - uses: actions/cache@v6
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: pub-${{ runner.os }}-

      - uses: vrchatapi/specification/.github/actions/setup@ci/modernise-actions
        with:
          bundle: openapi-legacy.yaml
          generator: 7.24.0

      - run: |
          mkdir -p ../vrchatapi-specification/dist
          mv openapi-legacy.yaml ../vrchatapi-specification/dist/

      - run: ./generate.sh local

      - run: dart analyze
        working-directory: vrchat_dart_generated
