on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-dart
          ref: ${{ inputs.ref || github.ref }}

      - uses: subosito/flutter-action@v2.23.0
        with:
          cache: true

      - uses: actions/cache@v6
        with:
          path: ${{ env.PUB_CACHE }}
          key: pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-

      - uses: actions/cache@v6
        with:
          path: |
            /home/linuxbrew/.linuxbrew
            /home/linuxbrew/.cache/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: ${{ runner.os }}-brew-

      - uses: Homebrew/actions/setup-homebrew@fd832223f9f99ebf0244dd20658680e5d4aca049

      - uses: vrchatapi/specification/.github/actions/setup@ci/modernise-actions
        with:
          bundle: openapi-legacy.yaml

      - run: |
          mkdir -p ../vrchatapi-specification/dist
          mv openapi-legacy.yaml ../vrchatapi-specification/dist/

      - run: ./generate.sh local

      - run: dart analyze
        working-directory: vrchat_dart_generated
