name: CI

on:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-dart
          ref: ${{ inputs.ref || github.ref }}

      - uses: dart-lang/setup-dart@v1.8.0

      - uses: vrchatapi/specification/.github/actions/setup-generator@main

      - uses: vrchatapi/specification/.github/actions/download@main
        with:
          bundle: openapi-3.0.yaml

      - run: |
          mkdir -p ../vrchatapi-specification/dist
          mv openapi-3.0.yaml ../vrchatapi-specification/dist/

      - run: ./generate.sh local

      - uses: actions/upload-artifact@v7
        with:
          name: dart-generated
          path: |
            .
            !.git/**
          include-hidden-files: true

  analyze:
    needs: generate
    uses: vrchatapi/vrchatapi-dart/.github/workflows/analyze.yaml@main
    with:
      artifact: dart-generated
