name: Generate

on:
  repository_dispatch:
    types: [release]
  workflow_dispatch:
    inputs:
      tag:
        description: Release to build, such as v1.22.1 or nightly.
        required: false
        type: string
        default: nightly

jobs:
  generate:
    if: ${{ !contains(github.event.client_payload.version || '', 'nightly') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2.23.0
        with:
          cache: true

      - name: Pub cache
        uses: actions/cache@v6
        env:
          cache-name: root
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ env.cache-name }}-

      - uses: vrchatapi/specification/.github/actions/setup-generator@main
      - uses: vrchatapi/specification/.github/actions/download@main
        with:
          bundle: openapi-3.0.json
          tag: ${{ inputs.tag }}
      - run: |
          mkdir -p ../vrchatapi-specification/dist
          mv openapi-3.0.json ../vrchatapi-specification/dist/
      - name: Generate
        run: ./generate.sh local

      - name: Check for CHANGELOG changes
        id: changelog
        run: |
          if git diff --quiet vrchat_dart_generated/CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changelog.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          branch: ci/regenerate-from-spec
          commit-message: "Regenerated from spec"
          title: "[CI] Regenerated from spec"
          body: "Regenerated from spec"
